/**
 * @file Message.js
 * @description Mongoose schema for the `messages` collection.
 *
 * Each document represents a single chat turn in a session.
 * Messages are scoped to a session and carry a `role` field
 * (either 'user' or 'agent') so the chat history can be replayed in order.
 *
 * The optional `structuredMeta` field holds any machine-readable data
 * attached to an agent message (e.g., a structured trip brief confirmation
 * or an intermediate search summary).
 */

'use strict';

const { Schema, model, Types } = require('mongoose');

const messageSchema = new Schema(
  {
    /** The session this message belongs to. */
    sessionId: {
      type: Types.ObjectId,
      ref: 'Session',
      required: [true, 'sessionId is required'],
    },

    /**
     * Who sent the message.
     * 'user' = typed by the human; 'agent' = generated by the Lead Agent.
     */
    role: {
      type: String,
      enum: ['user', 'agent'],
      required: [true, 'role is required'],
    },

    /** Plain-text or markdown content of the message. */
    content: {
      type: String,
      required: [true, 'content is required'],
      trim: true,
    },

    /**
     * Optional structured payload accompanying an agent message.
     * Example: { type: 'brief_confirmed', brief: { destination: 'Tokyo', ... } }
     */
    structuredMeta: {
      type: Object,
      default: null,
    },
  },
  {
    timestamps: true, // createdAt serves as the message timestamp
  }
);

// Index for efficient chat history queries ordered by creation time
messageSchema.index({ sessionId: 1, createdAt: 1 });

module.exports = model('Message', messageSchema);
